/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FfLvnX0Xdn0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"

export default function Hero() {
  return (
    <div className="flex flex-col min-h-screen">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="text-2xl font-bold" prefetch={false}>
          Event Platform
        </Link>
        <nav className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Events
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Organizers
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            About
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Contact
          </Link>
          <Button variant="secondary" size="sm">
            Sign In
          </Button>
        </nav>
      </header>
      <section
        className="bg-primary/10 py-12 px-6 flex flex-col items-center justify-center">
        <h1 className="text-4xl font-bold mb-4">Discover Upcoming Events</h1>
        <p className="text-muted-foreground mb-8">Find the best events in your area and get tickets now.</p>
        <div className="w-full max-w-md">
          <Input type="search" placeholder="Search events..." className="w-full" />
        </div>
      </section>
      <section className="py-12 px-6">
        <h2 className="text-2xl font-bold mb-6">Featured Events</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Music Festival</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>June 1, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>New York, NY</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Tech Conference</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>July 15, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>San Francisco, CA</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Art Exhibition</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>August 1, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>Los Angeles, CA</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="py-12 px-6">
        <h2 className="text-2xl font-bold mb-6">Upcoming Events</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Comedy Show</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>September 1, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>Chicago, IL</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Cooking Class</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>October 1, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>Seattle, WA</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
          <Card>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Event Image"
              className="rounded-t-lg object-cover w-full h-48" />
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Yoga Retreat</h3>
              <div className="flex items-center text-muted-foreground mb-2">
                <CalendarIcon className="w-4 h-4 mr-2" />
                <span>November 1, 2023</span>
              </div>
              <div className="flex items-center text-muted-foreground mb-4">
                <LocateIcon className="w-4 h-4 mr-2" />
                <span>Bali, Indonesia</span>
              </div>
              <Button size="sm">Buy Tickets</Button>
            </CardContent>
          </Card>
        </div>
      </section>
      <section className="bg-muted py-12 px-6">
        <h2 className="text-2xl font-bold mb-6">Organizer Dashboard</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <Card>
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Manage Events</h3>
              <p className="text-muted-foreground mb-4">Create, edit, and view your events.</p>
              <Button size="sm">Manage Events</Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Analytics</h3>
              <p className="text-muted-foreground mb-4">View detailed analytics for your events.</p>
              <Button size="sm">View Analytics</Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="p-4">
              <h3 className="text-xl font-bold mb-2">Create Event</h3>
              <p className="text-muted-foreground mb-4">Add a new event to your platform.</p>
              <Button size="sm">Create Event</Button>
            </CardContent>
          </Card>
        </div>
      </section>
      <footer
        className="bg-primary text-primary-foreground py-6 px-6 flex items-center justify-between">
        <p>&copy; 2023 Event Platform. All rights reserved.</p>
        <nav className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Privacy Policy
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Contact Us
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function LocateIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>)
  );
}
